#!/usr/bin/env python3
"""
export-globals-css.py
Generates a complete app/globals.css from assets/variables-export.json.
Outputs all four brand modes: :root (light), .dark, [data-theme="primary"], [data-theme="secondary"].

Usage:
  python3 scripts/export-globals-css.py
  python3 scripts/export-globals-css.py --out app/globals.css
"""

import json
import argparse
from pathlib import Path

ROOT   = Path(__file__).parent.parent
TOKENS = ROOT / "assets" / "variables-export.json"
OUTPUT = ROOT / "app" / "globals.css"

MODE_SELECTORS = {
    "light mode":  ":root",
    "dark mode":   ".dark",
    "primary":     '[data-theme="primary"]',
    "secondary":   '[data-theme="secondary"]',
}


def to_hex(r: float, g: float, b: float) -> str:
    return "#{:02x}{:02x}{:02x}".format(int(round(r*255)), int(round(g*255)), int(round(b*255)))


def css_value(mode_val: dict) -> str:
    v = mode_val.get("value", {})
    if isinstance(v, dict) and "r" in v:
        a = v.get("a", 1)
        h = to_hex(v["r"], v["g"], v["b"])
        if a != 1:
            return "rgb({} {} {} / {})".format(
                int(round(v["r"]*255)), int(round(v["g"]*255)), int(round(v["b"]*255)), round(a, 2))
        return h
    return str(v)


def generate(tokens_path: Path, output_path: Path) -> None:
    with open(tokens_path) as f:
        data = json.load(f)

    shadcn = [v for v in data["variables"] if v["collectionName"] == "shadcn/ui"]

    # Group by CSS mode
    by_mode: dict[str, dict[str, str]] = {m: {} for m in MODE_SELECTORS}
    for var in shadcn:
        n = var["name"]
        for mode_name in MODE_SELECTORS:
            mv = var["valuesByMode"].get(mode_name, {})
            if mv:
                by_mode[mode_name][n] = css_value(mv)

    lines: list[str] = []
    w = lines.append

    w('@import "tailwindcss";')
    w('@import "tw-animate-css";')
    w("")
    w("@custom-variant dark (&:is(.dark *));")
    w("")
    w("/*")
    w(f" * Generated by scripts/export-globals-css.py from {tokens_path.name}")
    w(f" * Source: lazyyysync-variables-v1 · shadcn/ui collection · {len(shadcn)} tokens × 4 modes")
    w(" * Do not edit values by hand — re-export from Figma and regenerate.")
    w(" */")
    w("")

    for mode_name, selector in MODE_SELECTORS.items():
        label = mode_name.replace(" mode", "")
        w(f"{selector} {{")
        w(f"  /* {label} */")
        w("  --radius: 0.5rem;")
        for name, val in by_mode[mode_name].items():
            w(f"  --{name}: {val};")
        w("}")
        w("")

    # @theme inline — map CSS vars → Tailwind utilities
    w("@theme inline {")
    w("  /* ── Colors ─────────────────────────────────── */")
    for var in shadcn:
        n = var["name"]
        w(f"  --color-{n}: var(--{n});")
    w("")
    w("  /* ── Radius scale (static) ──────────────────── */")
    radius_map = {"xs":"0.125rem","sm":"0.25rem","md":"0.375rem","lg":"0.5rem",
                  "xl":"0.75rem","2xl":"1rem","3xl":"1.5rem","4xl":"2rem"}
    for k, v in radius_map.items():
        w(f"  --radius-{k}: {v};")
    w("")
    w("  /* ── Fonts ──────────────────────────────────── */")
    w('  --font-sans: "Inter", ui-sans-serif, system-ui, sans-serif;')
    w('  --font-mono: "Geist Mono", ui-monospace, SFMono-Regular, monospace;')
    w("")
    w("  /* ── Shadow override ────────────────────────── */")
    w("  --shadow-xs: 0 1px 2px 0 rgb(0 0 0 / 0.1);")
    w("}")
    w("")
    w("@layer base {")
    w("  * {")
    w("    @apply border-border outline-ring/50;")
    w("  }")
    w("  body {")
    w("    @apply bg-background text-foreground;")
    w("  }")
    w("}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"Written: {output_path}")
    print(f"  {len(shadcn)} semantic tokens · 4 modes ({', '.join(MODE_SELECTORS.values())})")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate globals.css from design tokens")
    parser.add_argument("--tokens", default=str(TOKENS))
    parser.add_argument("--out",    default=str(OUTPUT))
    args = parser.parse_args()
    generate(Path(args.tokens), Path(args.out))
